---
collections:

  - name: infrastructure.provision
    version: 1.0.0

  - name: database.oracle
    version: 1.0.0
    
  - name: database.sqlserver
    version: 1.0.1

  - name: ansible.controller
    version: 4.5.2
    
  - name: community.general
    version: 4.8.0
    source: https://galaxy.ansible.com

  - name: ansible.posix
    version: 1.5.4
    source: https://galaxy.ansible.com

  - name: ansible.utils
    version: 4.1.0
    source: https://galaxy.ansible.com
