---
# tasks file for oracle_backup
- name: Get current date
  ansible.builtin.set_fact:
    backup_time: "{{ ansible_date_time.iso8601_basic_short }}"
  when: inventory_hostname == origin

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "/home/oracle/backups/{{ origin }}/backup_{{ backup_time }}"
    - "/home/oracle/backups/{{ origin }}/controlfile"
    - "/home/oracle/backups/{{ target }}"
  when: inventory_hostname == origin

- name: Mount target server mountpoint
  ansible.posix.mount:
    src: "{{ hostvars[origin]['ansible_facts']['eth0']['ipv4']['address'] }}:/home/oracle/backups/{{ origin }}"
    path: "/home/oracle/backups/{{ origin }}"
    opts: rw,sync,hard
    boot: true
    state: mounted
    fstype: nfs
  become: true
  become_user: root
  when: inventory_hostname == target

- name: Template RMAN Script using provided variables
  ansible.builtin.template:
    src: "backup.rmn.j2"
    dest: "/tmp/backup_{{ backup_time }}.rmn"
    mode: "0755"
  register: backup_script
  when: inventory_hostname == origin

- name: Execute RMAN operation
  ansible.builtin.shell: "source .bash_profile && rman target / nocatalog < {{ backup_script.dest }} log=full_back.log"
  args:
    chdir: /home/oracle
    executable: /bin/bash
  register: backup_result
  changed_when: "backup_result.rc == 0"
  failed_when: "backup_result.rc != 0"
  when: inventory_hostname == origin
