---


- name: Mount target server mountpoint
  ansible.posix.mount:
    src: "{{ hostvars[origin]['ansible_facts']['eth0']['ipv4']['address'] }}:/home/oracle/backups/{{ origin }}"
    path: "/home/oracle/backups/{{ origin }}"
    opts: rw,sync,hard
    boot: true
    state: mounted
    fstype: nfs
  become: true
  become_user: root
  when: inventory_hostname == target

- name: Get DB id
  ansible.buil

- name: Template RMAN Script using provided variables
  ansible.builtin.template:
    src: "restore.rmn.j2"
    dest: "/tmp/restore.rman"
    mode: "0755"
  register: backup_script
  when: inventory_hostname == target