---
  - name: Set hostname
    ansible.builtin.hostname:
      name: "{{ inventory_hostname }}"

  - name: Add entry to hosts file
    ansible.builtin.lineinfile:
      line: "{{ private_ipv4_addresses.0 }} {{ inventory_hostname }}"
      path: /etc/hosts

  - name: Install dependencies
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
      - bc
      - bind-utils 
      - compat-openssl10 
      - glibc-devel
      - initscripts
      - ksh
      - libaio
      - libnsl
      - make
      - net-tools
      - smartmontools
      - sysstat
      - unzip
      - xorg-x11-utils
      - xorg-x11-xauth
      - git
      - nfs-utils

  - name: Disable Firewalld
    ansible.builtin.service:
      name: firewalld
      state: stopped
      enabled: false

  - name: Copy Oracle Scripts
    ansible.posix.synchronize:
      src: "./files"
      dest: "/home/oracle"

  - name: Install Oracle Preinstallation Package
    ansible.builtin.dnf:
      name: "{{ preinstall_package_url }}"
      state: present
      validate_certs: false
      sslverify: false
      disable_gpg_check: true

  - name: Install Oracle Installation Package
    ansible.builtin.dnf:
      name: "{{ install_package_url }}"
      state: present
      validate_certs: false
      sslverify: false
      disable_gpg_check: true

  - name: Set Initial Configuration for Oracle
    ansible.builtin.shell:
     cmd: "/etc/init.d/{{ installation_executable }} configure"
    environment:
      ORACLE_PASSWORD: "{{ lookup('ansible.builtin.env', 'ORACLE_PASSWORD') }}"
    register: install_output

  - name: Create NFS Shared directory
    ansible.builtin.file:
      path: "/home/oracle/backups/{{ vm_hostname }}"
      state: directory

  - name: Set permissions
    ansible.builtin.file:
      path: "{{ item }}"
      owner: oracle
      group: oinstall
      mode: "0755"
      recurse: yes
    loop:
      - "/home/oracle/files"
      - "/home/oracle/backups/{{ vm_hostname }}"

  - name: Create NFS exports configuration
    ansible.builtin.lineinfile:
      path: "/etc/exports"
      line: "/home/oracle/backups/{{ vm_hostname }} *(rw,sync,no_root_squash,no_subtree_check)"
      insertafter: EOF

  - name: Enable Services 
    ansible.builtin.service:
      name: "{{ item }}"
      state: started
      enabled: true
    loop:
      - rpcbind
      - nfs-server

  - name: Set variables
    ansible.builtin.set_stats:
      data:
        vm_hostname: "{{ vm_hostname }}"