---
  - name: Set hostname
    ansible.builtin.hostname:
      name: "{{ inventory_hostname }}"

  - name: Add entry to hosts file
    ansible.builtin.lineinfile:
      line: "{{ private_ipv4_addresses.0 }} {{ inventory_hostname }}"
      path: /etc/hosts

  - name: Install dependencies
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
      - bc
      - bind-utils 
      - compat-openssl10 
      - glibc-devel
      - initscripts
      - ksh
      - libaio
      - libnsl
      - make
      - net-tools
      - smartmontools
      - sysstat
      - unzip
      - xorg-x11-utils
      - xorg-x11-xauth
      - git

  - name: Disable Firewalld
    ansible.builtin.service:
      name: firewalld
      state: stopped
      enabled: false

  - name: Copy Oracle Scripts
    ansible.builtin.synchronize:
      src: "./files"
      dest: "/home/oracle"
      owner: oracle
      group: oinstall
  
  - name: Install Oracle Preinstallation Package
    ansible.builtin.dnf:
      name: "{{ preinstall_package_url }}"
      state: present
      validate_certs: false
      sslverify: false
      disable_gpg_check: true

  - name: Install Oracle Installation Package
    ansible.builtin.dnf:
      name: "{{ install_package_url }}"
      state: present
      validate_certs: false
      sslverify: false
      disable_gpg_check: true

  - name: Set Initial Configuration for Oracle
    ansible.builtin.shell:
      cmd: "/etc/init.d/{{ installation_executable }} configure"
    environment:
      ORACLE_PASSWORD: "{{ lookup('ansible.builtin.env', 'ORACLE_PASSWORD') }}"
    register: install_output

