---
- name: Template SQL Sentence using provided variables
  ansible.builtin.template:
    src: "{{ operation }}.sql.j2"
    dest: "/tmp/{{ operation }}_{{ ansible_date_time.iso8601 }}.sql"
    mode: "0755"
  register: sql_script
  when: operation != "execute_script"

- name: Execute SQL operation as SA User
  ansible.builtin.shell: "sqlcmd -C -S localhost -U SA -i {{ sql_script.dest }} -b"
  args:
    executable: /bin/bash
  register: query_result
  environment:
    SQLCMDPASSWORD: "{{ lookup('ansible.builtin.env', 'MSSQL_PASSWORD') }}"
  changed_when: "query_result.rc == 0"
  failed_when: "query_result.rc != 0"
  when: operation != "execute_script"

- name: Execute SQL operation as SA User
  ansible.builtin.shell: "sqlcmd -C -S localhost -U SA -i {{ script_filename }} -b"
  args:
    executable: /bin/bash
  register: query_result
  environment:
    SQLCMDPASSWORD: "{{ lookup('ansible.builtin.env', 'MSSQL_PASSWORD') }}"
  changed_when: "query_result.rc == 0"
  failed_when: "query_result.rc != 0"
  when: operation == "execute_script"

- name: Clean temporary files
  ansible.builtin.file:
    path: "{{ sql_script.dest }}"
    state: absent
  when: operation != "execute_script"