---
- name: Execute Script
  hosts: "{{ vm_hostname }}"
  gather_facts: true
  become: true
  roles:
    - role: database.sqlserver.sqlserver_operations
      vars:
        operation: execute_script
        script_filename: "{{ script_filename }}"