---
- name: Create SQL Server User
  hosts: "{{ vm_hostname }}"
  gather_facts: true
  become: true
  environment: 
    PATH: $PATH:$HOME/bin:/opt/mssql-tools18/bin
  roles:
    - role: database.sqlserver.sqlserver_operations
      vars:
        operation: create_user
        db_username: "{{ username }}"
        db_password: "{{ password }}"
