---
- name: Create SQL Server Backup
  hosts: all
  gather_facts: true
  become: true
  become_user: mssql
  environment: 
    PATH: /usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/var/opt/mssql/bin:/opt/mssql-tools18/bin
  roles:
    - role: database.sqlserver.sqlserver_backup
      vars:
        operation: backup
        origin: "{{ origin }}"