---
- name: Create SQL Server Backup
  hosts: all
  gather_facts: true
  become: true
  become_user: mssql
  environment: 
    PATH: $PATH:$HOME/bin:/opt/mssql-tools18/bin
  roles:
    - role: database.sqlserver.sqlserver_backup
      vars:
        operation: restore
        backup: "{{ backup }}"
        target: "{{ target }}"
