---
- name: Execute Script
  hosts: "{{ vm_hostname }}"
  gather_facts: true
  become: true
  become_user: mssql
  environment: 
    PATH: $PATH:$HOME/bin:/opt/mssql-tools18/bin
  roles:
    - role: database.sqlserver.sqlserver_operations
      vars:
        operation: execute_script
        script_filename: "{{ script_filename }}"