---
- name: Create SQL Server Backup
  hosts: all
  gather_facts: true
  become: true
  become_user: mssql
  roles:
    - role: database.sqlserver.sqlserver_backup
      vars:
        operation: backup
        origin: "{{ origin }}"