---
- name: Update MSSQL Restore Job
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Update Controller's Restore Job Template
      ansible.controller.job_template:
        controller_host: "https://{{ lookup('ansible.builtin.env', 'CONTROLLER_HOST') }}"
        controller_username: "{{ lookup('ansible.builtin.env', 'CONTROLLER_USERNAME') }}"
        controller_password: "{{ lookup('ansible.builtin.env', 'CONTROLLER_PASSWORD') }}"
        validate_certs: false
        name: "[JT] [MSSQL] Restore Backup"
        job_type: "run"
        organization: "databasedemo"
        inventory: "Microsoft Azure"
        project: "Ansible Databases Demo Project"
        playbook: "playbooks/sqlserver/mssql_restore_backup.yml"
        credentials:
          - "MSSQL SA Credential"
          - "RHEL Managed Hosts Credential"
        execution_environment: "Azure Execution Environment"
        limit: db_mssql
        survey_enabled: true
        survey_spec: "{{ survey }}"
        state: present
