---
  - name: Template SQL Sentence using provided variables
    ansible.builtin.template:
      src: create_user.sql.j2
      dest: /tmp/create_user_{{ ansible_date_time.iso8601 }}.sql
    register: new_user

  - name: Create Oracle User
    ansible.builtin.shell: "source .bash_profile && sqlplus / as sysdba < {{ new_user.dest }}"
    args:
      chdir: /hom/oracle
      executable: /bin/bash
    register: query_result
    changed_when: "query_result.rc == 0"
    failed_when: "query_result.rc != 0"

  - name: Clean temporary files
    ansible.builtin.file:
      path: "{{ new_user.dest }}"
      state: absent
