---
- name: Deploy Oracle Virtual Machine
  hosts: localhost
  gather_facts: false
  roles:
    - role: infrastructure.provision.azure_infra
    - role: infrastructure.provision.azure_vm
      vars:
        os_type: "{{ os_type }}" # Example: Linux
        vm_name: "{{ vm_hostname }}"
        vm_size: "{{ vm_size }}" # Example: Standard_DS1_v2
