---
# tasks file for azure_disk_resize

  - name: Resize partitions
    community.general.lvol:
      vg: rootvg
      lv: "{{ item }}"
      size: +30%FREE
    loop:
      - rootlv
      - tmplv
      - homelv
      - usrlv
      - varlv

  - name: Create a filesystem on top of a regular file
    community.general.filesystem:
      dev: "/dev/rootvg/{{ item }}"
      fstype: xfs
      resizefs: true
    loop:
      - rootlv
      - tmplv
      - homelv
      - usrlv
      - varlv
