---
# tasks file for azure_disk_resize

  - name: Extend to fill all available space
    ansible.builtin.command: "growpart /dev/sdb 2"
    register: partition_output
    changed_when: partition_output.rc == 0

  - name: Extend Physuical Volume
    ansible.builtin.command: "pvresize /dev/sdb2"
    register: pv_output
    changed_when: pv_output.rc == 0

  - name: Resize volume group
    community.general.lvg:
      vg: rootvg
      pvs: /dev/sdb2

  - name: Resize partitions
    community.general.lvol:
      vg: rootvg
      lv: "{{ item }}"
      size: +20%FREE
    loop:
      - rootlv
      - tmplv
      - homelv
      - usrlv
      - varlv

  - name: Resize Filesystems
    community.general.filesystem:
      dev: "/dev/rootvg/{{ item }}"
      fstype: xfs
      resizefs: true
    loop:
      - rootlv
      - tmplv
      - homelv
      - usrlv
      - varlv
