scm_credentials:
  - name: "Red Hat Ansible Automation Platform Credential"
    desc: "Red Hat Ansible Automation Platform Credential"
    org: "{{ default_organization | default('Default') }}"
    type: "Red Hat Ansible Automation Platform"
    inputs:
      host: "{{ aap_host }}" # Ansible Controller URL
      username: "{{ aap_user }}" # Ansible Controller Username
      password: "{{ aap_pass }}" # Ansible Controller Password

  - name: "Red Hat Ansible Automation Hub Credential"
    desc: "Red Hat Ansible Automation Hub Credential"
    org: "{{ default_organization | default('Default') }}"
    type: "Red Hat Ansible Automation Hub"
    inputs:
      hub_host: "{{ hub_host }}" # Automation Hub URL
      hub_user: "{{ hub_user }}" # Automation Hub Username
      hub_pass: "{{ hub_pass }}" # Automation Hub Password

  - name: "Automation Hub Api Token for Published repository"
    desc: "Automation Hub Credential"
    org: "{{ default_organization | default('Default') }}"
    type: "Ansible Galaxy/Automation Hub API Token"
    inputs:
      url: "https://{{ hub_host }}/api/galaxy"
      token: "{{ ansible_facts.ah_token.token }}"

  - name: "Automation Hub Api Token for Red Hat Certified repository"
    desc: "Automation Hub Credential"
    org: "{{ default_organization | default('Default') }}"
    type: "Ansible Galaxy/Automation Hub API Token"
    inputs:
      url: "https://{{ hub_host }}/api/galaxy/content/rh-certified"
      token: "{{ ansible_facts.ah_token.token }}"

  - name: "Microsoft Azure Credential"
    desc: "Microsoft Azure Credential"
    org: "{{ default_organization | default('Default') }}"
    type: "Microsoft Azure Resource Manager"
    inputs:
      client: "{{ azure_client_id }}" # Azure Client ID 
      secret: "{{ azure_secret }}" # Azure Secret
      subscription: "{{ azure_subscription_id }}" # Azure Subscription ID
      tenant: "{{ azure_tenant }}" # Azure Tenant
      #cloud_environment: "{{ azure_cloud_environment }}" # Azure Cloud Environment

  - name: "Microsoft Azure Resource Group"
    desc: "Microsoft Azure Resource Group"
    org: "{{ default_organization | default('Default') }}"
    type: "Microsoft Azure Resource Group"
    inputs:
      azure_resource_group: "{{ azure_resource_group }}" # Azure Resource Group 

  - name: "SSH Public Key"
    desc: "SSH Public Key"
    org: "{{ default_organization | default('Default') }}"
    type: "SSH Public Key"
    inputs:
      public_key: "{{ lookup('ansible.builtin.file', rhel_public_rsa_file ) }}" # SSH Public Key  

  - name: "Oracle Sysdba Credential"
    desc: "Oracle Sysdba Credential"
    org: "{{ default_organization | default('Default') }}"
    type: "Oracle Sysdba Credential"
    inputs:
      oracle_password: "{{ oracle_password }}" # Oracle Password 

  - name: "MSSQL SA Credential"
    desc: "MSSQL SA Credential"
    org: "{{ default_organization | default('Default') }}"
    type: "MSSQL SA Credential"
    inputs:
      mssql_password: "{{ mssql_password }}" # MSSQL Password 

  - name: "Oracle HR User Credential"
    desc: "Oracle HR User Credential"
    org: "{{ default_organization | default('Default') }}"
    type: "Oracle Database User Credential"
    inputs:
      oracle_database_username: "{{ oracle_user_username }}"
      oracle_database_password: "{{ oracle_user_pass }}" # Oracle Password 

  - name: "RHEL Managed Hosts Credential"
    desc: "RHEL Managed Hosts Credential"
    org: "{{ default_organization | default('Default') }}"
    type: "Machine"
    inputs:
      username: "{{ rhel_username }}" # RHEL Managed Hosts Username
      ssh_key_data: "{{ lookup('ansible.builtin.file', rhel_priv_rsa_file ) }}" # RHEL Managed Hosts private Key
