scm_credentials:
  - name: "Red Hat Ansible Automation Platform Credential"
    desc: "Red Hat Ansible Automation Platform Credential"
    org: Default
    type: "Red Hat Ansible Automation Platform"
    inputs:
      host: "{{ aap_host }}" # Ansible Controller URL
      username: "{{ aap_user }}" # Ansible Controller Username
      password: "{{ aap_pass }}" # Ansible Controller Password

  - name: "Red Hat Ansible Automation Hub Credential"
    desc: "Red Hat Ansible Automation Hub Credential"
    org: Default
    type: "Red Hat Ansible Automation Hub"
    inputs:
      hub_host: "{{ hub_host }}" # Automation Hub URL
      hub_user: "{{ hub_user }}" # Automation Hub Username
      hub_pass: "{{ hub_pass }}" # Automation Hub Password

  - name: "Automation Hub Api Token"
    desc: "Automation Hub Credential"
    org: Default
    type: "Ansible Galaxy/Automation Hub API Token"
    inputs:
      url: "https://{{ hub_host }}/api/galaxy"
      token: "{{ ansible_facts.ah_token.token }}" # RHEL Managed Hosts Username

  - name: "Microsoft Azure Credential"
    desc: "Microsoft Azure Credential"
    org: Default
    type: "Microsoft Azure Resource Manager"
    inputs:
      client: "{{ azure_client_id }}" # Azure Client ID 
      secret: "{{ azure_secret }}" # Azure Secret
      subscription: "{{ azure_subscription_id }}" # Azure Subscription ID
      tenant: "{{ azure_tenant }}" # Azure Tenant
      #cloud_environment: "{{ azure_cloud_environment }}" # Azure Cloud Environment

  - name: "Microsoft Azure Resource Group"
    desc: "Microsoft Azure Resource Group"
    org: Default
    type: "Microsoft Azure Resource Group"
    inputs:
      azure_resource_group: "{{ azure_resource_group }}" # Azure Resource Group 

  - name: "SSH Public Key"
    desc: "SSH Public Key"
    org: Default
    type: "SSH Public Key"
    inputs:
      public_key: "{{ lookup('ansible.builtin.file', rhel_public_rsa_file ) }}" # SSH Public Key  

  - name: "RHEL Managed Hosts Credential"
    desc: "RHEL Managed Hosts Credential"
    org: Default
    type: "Machine"
    inputs:
      username: "{{ rhel_username }}" # RHEL Managed Hosts Username
      ssh_key_data: "{{ lookup('ansible.builtin.file', rhel_priv_rsa_file ) }}" # RHEL Managed Hosts private Key
