---
- name: Create Oracle User
  hosts: "{{ vm_hostname }}"
  gather_facts: true
  become: true
  become_user: oracle
  roles:
    - role: database.oracle.oracle_operations
      vars:
        operation: create_user
        db_username: "{{ username }}"
        db_password: "{{ password }}"