---
- name: Create Oracle Backup
  hosts: all
  gather_facts: true
  become: true
  become_user: oracle
  roles:
    - role: database.oracle.oracle_backup
      vars:
        origin: "{{ origin }}"
        target: "{{ target }}"