---
- name: Create Oracle User
  hosts: Oracle-01
  gather_facts: true
  become: true
  become_user: oracle
  roles:
    - role: database.oracle.oracle_operations
      vars:
        operation: create_user
        db_username: "{{ oracle_user_username }}"
        db_password: "{{ oracle_user_password }}"