---
- name: Deploy Database Virtual Machine
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Deploy Azure Network
      ansible.builtin.import_role:
        name: infrastructure.provision.azure_infra

    - name: Deploy Azure Virtual Machine
      ansible.builtin.import_role:
        name: infrastructure.provision.azure_vm
      vars:
        os_type: Linux
        vm_name: test-01
        vm_size: Standard_DS1_v2
