---
- name: Deploy Azure Virtual Machine
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Deploy Azure Network
      ansible.builtin.import_role:
        name: infrastructure.provision.azure_infra


    - name: Deploy Azure Visrtual Machine
      ansible.builtin.import_role:
        name: infrastructure.provision.azure_vm
