---
- name: Deploy Oracle Virtual Machine
  hosts: localhost
  gather_facts: false
  roles:
    - role: infrastructure.provision.azure_infra
    - role: infrastructure.provision.azure_vm
      vars:
        os_type: Linux
        vm_name: Oracle-01
        vm_size: Standard_DS1_v2
    - role: database.oracle.oracle_install