---
- name: Build collections and upload them to the Automation Hub
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Build Collections
      infra.ah_configuration.ah_build:
        path: ../ansible-collections/database/oracle
        force: true
        output_path: /tmp

    - name: Upload collections to automation hub
      infra.ah_configuration.ah_collection_upload:
        path: /tmp/database-oracle-1.0.0.tar.gz
        validate_certs: false

    - name: Approve namespace.collection_name:v1.0.0
      infra.ah_configuration.ah_approval:
        namespace: database
        name: oracle
        version: 1.0.0
        validate_certs: false
